md_10/HW/quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls')),
]

md_10/HW/quotes/users/urls.py
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginuser, name='login'),
    path('signup/', views.signupuser, name='signup'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url='/users/reset-password/complete/'), name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

md_10/HW/quotes/users/models.py
from django.db import models

# Create your models here.

# from django.db import models
# from django.contrib.auth.models import User
# from PIL import Image
#
#
# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     avatar = models.ImageField(default='default_avatar.png', upload_to='profile_images')
#
#     def __str__(self):
#         return self.user.username
#
#     # resizing images
#     def save(self, *args, **kwargs):
#         super().save()
#
#         img = Image.open(self.avatar.path)
#
#         if img.height > 250 or img.width > 250:
#             new_img = (250, 250)
#             img.thumbnail(new_img)
#             img.save(self.avatar.path)

md_10/HW/quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

# from .models import Profile


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    email = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

md_10/HW/quotes/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy

from .forms import LoginForm, RegisterForm


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotesapp:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'users/signup.html', context={'form': form})

    return render(request, 'users/signup.html', context={'form': RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='quotesapp:main')

    if request.method == 'POST':
        user = authenticate(
            username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='quotesapp:main')

    return render(request, 'users/login.html', context={'form': LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='quotesapp:main')

md_10/HW/quotes/users/templates/users/login.html
{% extends 'quotesapp/base.html' %} {% block content %}
<div>
    <h2>Log in</h2>
</div>
{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
<form action="{% url 'users:login' %}" method="post" accept-charset="utf-8">
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-xs-3">
                <label for="username">Username</label>
                {{ form.username }}
<!--                <input type="text" class="form-control" id="username" name="username">-->
            </div>
        </div>
        <div class="row">
            <div class="form-group col-xs-3">
                <label for="username">Password</label>
                {{ form.password }}
<!--                <input type="password" class="form-control" id="password" name="password">-->
            </div>
        </div>
        <input type="submit" value="Login" class="btn btn-primary">
        <div class="small text-center">
            <a href="{% url 'users:password_reset' %}" class="text-center">
                <i>Forgot password?</i>
            </a>
        </div>
    </form>
{% endblock %}

md_10/HW/quotes/users/templates/users/password_reset.html
{% extends 'quotesapp/base.html' %}

{% block content %}

<h2>Reset password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset password</button>
</form>
{% endblock %}

md_10/HW/quotes/users/templates/users/password_reset_complete.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h2>Password reset complete</h2>

{% endblock %}

md_10/HW/quotes/users/templates/users/password_reset_confirm.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

md_10/HW/quotes/users/templates/users/password_reset_done.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password</p>

{% endblock %}

md_10/HW/quotes/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

md_10/HW/quotes/users/templates/users/signup.html
{% extends 'quotesapp/base.html' %} {% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form action="{% url 'users:signup' %}" method="post" accept-charset="utf-8">
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-xs-3">
                <label for="username">Username</label>
                {{ form.username }}
                <span>{{ form.errors.username }}</span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-xs-3">
                <label for="email">Email</label>
                {{ form.email }}
                <span>{{ form.errors.email }}</span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-xs-3">
                <label for="username">Password</label>
                {{ form.password1 }}
                <span>{{ form.errors.password1 }}</span>
            </div>
         <div class="row">
            <div class="form-group col-xs-3">
                <label for="username">Password confirmation</label>
                {{ form.password2 }}
                <span>{{ form.errors.password2 }}</span>
            </div>
        </div>
        <input type="submit" value="Sign up" class="btn btn-primary">
    </div>
    </form>
{% endblock %}