md_10/HW/quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls')),
]

md_10/HW/quotes/quotesapp/urls.py
from django.urls import path

from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('scrape/', views.scrape_quotes, name='scrape'),
    path('tag/<str:tag_name>/', views.tag, name='tag'),
    path('author/<str:author_name>/', views.author_info, name='author'),
    path('add/author/', views.add_author, name='author_form'),
    path('add/quote/', views.add_quote, name='quote_form'),
]

md_10/HW/quotes/users/urls.py
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginuser, name='login'),
    path('signup/', views.signupuser, name='signup'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/',
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url='/users/reset-password/complete/'), name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

md_10/HW/quotes/quotesapp/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=100, unique=True)
    born_date = models.DateField(default=None, null=True)  # %B %d, %Y - March 14, 1879
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True, null=False)


class Quote(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    tags = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)

md_10/HW/quotes/quotesapp/forms.py
from django.forms import ModelForm, CharField, DateField, TextInput, DateInput, Textarea
from .models import Author, Tag, Quote


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True)

    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(ModelForm):
    fullname = CharField(min_length=5, max_length=100, widget=TextInput())
    born_date = DateField(widget=DateInput(), help_text="Valid date format 'mm/dd/yyyy'")
    born_location = CharField(min_length=5, max_length=150, widget=TextInput())
    description = CharField(min_length=10, max_length=255, widget=Textarea())

    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']


class QuoteForm(ModelForm):
    quote = CharField(min_length=10, max_length=255, widget=Textarea())

    class Meta:
        model = Quote
        fields = ['quote']

md_10/HW/quotes/quotesapp/views.py
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from .forms import AuthorForm, QuoteForm
from .models import Quote, Author, Tag
from utils import scrape_quotes_to_db  # noqa


# Create your views here.
def main(request):
    tags_with_count = Tag.objects.annotate(usage_count=Count('quote')) # noqa
    top_10_tags = sorted(tags_with_count, key=lambda x: x.usage_count, reverse=True)[:10]
    quotes = Quote.objects.all() # noqa
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    page_number = request.GET.get('page')
    if not page_number:
        page_obj = paginator.get_page(number='1')
    else:
        page_obj = paginator.get_page(page_number)
    return render(request, 'quotesapp/quotes.html', {'page_obj': page_obj, 'top_tags': top_10_tags})


def tag(request, tag_name):
    tags_with_count = Tag.objects.annotate(usage_count=Count('quote')) # noqa
    top_10_tags = sorted(tags_with_count, key=lambda x: x.usage_count, reverse=True)[:10]
    quotes = Quote.objects.filter(tags__name=tag_name) # noqa
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    page_number = request.GET.get('page')
    if not page_number:
        page_obj = paginator.get_page(number='1')
    else:
        page_obj = paginator.get_page(page_number)
    return render(request, 'quotesapp/quotes.html', {'page_obj': page_obj, 'tag': tag_name, 'top_tags': top_10_tags})


def author_info(request, author_name):
    author = Author.objects.filter(fullname=author_name)[0] # noqa
    return render(request, 'quotesapp/author.html', {'author': author})


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/author_form.html', {"form": form})

    return render(request, 'quotesapp/author_form.html', {"form": AuthorForm()})


@login_required
def add_quote(request):
    tags = Tag.objects.all() # noqa
    authors = Author.objects.all() # noqa

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            author = Author.objects.filter(fullname=request.POST.get('author'))[0]
            new_quote.author = author
            new_quote.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/quote_form.html', {"tags": tags, "authors": authors, "form": form})

    return render(request, 'quotesapp/quote_form.html', {"tags": tags, "authors": authors, "form": QuoteForm()})


def scrape_quotes(request):
    scrape_quotes_to_db()
    return redirect(to='quotesapp:main')

md_10/HW/quotes/quotesapp/templates/quotesapp/author.html
{% extends 'quotesapp/base.html' %}
{% block content %}
<div class="author-details">
    <h3 class="author-title">{{ author.fullname }}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date|date:'F d, Y' }}</span> <span class="author-born-location">{{ author.born_location }}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{ author.description }}
    </div>
</div>
{% endblock %}

md_10/HW/quotes/quotesapp/templates/quotesapp/author_form.html
{% extends "quotesapp/base.html" %}

{% block content %}
<form method="POST" action="{% url 'quotesapp:author_form' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author name:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born date:
            {{ form.born_date }}
        </label>
        <span> {{ form.born_date.help_text }}</span>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

md_10/HW/quotes/quotesapp/templates/quotesapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My homework</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'quotesapp/main.css' %}">
</head>
<body>
<div class="container">
    <div class="row header-box">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                {% if user.is_authenticated %}
                <a>Welcome <b>{{ user.username }}!</b></a>
                    {% if user.username == 'admin' %}
                    <a href="{% url 'quotesapp:scrape' %}">Scrape data</a>
                    {% endif %}
                <a href="{% url 'quotesapp:quote_form' %}">Add quote</a>
                <a href="{% url 'quotesapp:author_form' %}">Add author</a>
                <a href="{% url 'users:logout' %}">Logout</a>
                {% else %}
                <a href="{% url 'users:signup' %}">Signup</a>
                <a href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </p>
        </div>
    </div>

    {% block content %} {% endblock %}

</div>
<footer class="footer">
    <div class="container">
        <p class="text-muted">
            Quotes by: <a href="https://www.goodreads.com/quotes">GoodReads.com</a>
        </p>
        <p class="copyright">
            Made with <span class='zyte'>❤</span> by <a class='zyte' href="https://www.zyte.com">Zyte</a>
        </p>
    </div>
</footer>
</body>
</html>

md_10/HW/quotes/quotesapp/templates/quotesapp/quote_form.html
{% extends "quotesapp/base.html" %} {% load sort_list %}

{% block content %}
<form method="POST" action="{% url 'quotesapp:quote_form' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote text:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="author">
                {% for author in authors|sort %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple">
                {% for tag in tags|sort %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

md_10/HW/quotes/quotesapp/templates/quotesapp/quotes.html
{% extends "quotesapp/base.html" %} {% load extract_tags %} {% block content %}

<div class="row">
    <div class="col-md-8">
        {% if tag %}
        <h3>Viewing tag: <a href="/tag/{{ tag }}">{{ tag }}</a></h3>
        {% endif %}
        {% for quote in page_obj %}
        <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">“{{ quote.quote }}”</span>
            <span>by <small class="author" itemprop="author">{{ quote.author.fullname}}</small>
        <a href="/author/{{ quote.author.fullname }}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                <meta class="keywords" itemprop="keywords" content="{{ quote.tags | tags }}"/>
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{ tag.name }}">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        <nav>
            <ul class="pager">
                {% if page_obj.has_previous %}
                <li class="previous">
                    <a href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">&larr;</span> Previous</a>
                </li>
                {% endif %}

                {% if page_obj.has_next %}
                <li class="next">
                    <a href="?page={{ page_obj.next_page_number }}">Next <span aria-hidden="true">&rarr;</span></a>
                </li>
                {% endif %}
            </ul>
        </nav>

    </div>
    <div class="col-md-4 tags-box">

        <h2>Top Ten tags</h2>
        {% for tag in top_tags %}
        <span class="tag-item">
            <a class="tag" style="font-size: {% cycle '28' '26' '26' '24' '22' '14' '10' '8' '8' '6' %}px" href="/tag/{{ tag.name }}">{{ tag.name }}</a>
            </span>
        {% endfor %}



    </div>
</div>
{% endblock %}